call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 4 integer vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 4 integer map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 4 integer unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 4 integer flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 4 integer vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 4 integer map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 4 integer unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 4 integer flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 4 integer vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 4 integer map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 4 integer unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 4 integer flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 4 integer vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 4 integer map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 4 integer unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 4 integer flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 16 integer vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 16 integer map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 16 integer unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 16 integer flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 16 integer vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 16 integer map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 16 integer unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 16 integer flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 16 integer vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 16 integer map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 16 integer unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 16 integer flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 16 integer vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 16 integer map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 16 integer unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 16 integer flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 64 integer vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 64 integer map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 64 integer unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 64 integer flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 64 integer vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 64 integer map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 64 integer unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 64 integer flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 64 integer vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 64 integer map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 64 integer unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 64 integer flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 64 integer vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 64 integer map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 64 integer unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 64 integer flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 256 integer vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 256 integer map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 256 integer unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 256 integer flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 256 integer vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 256 integer map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 256 integer unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 256 integer flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 256 integer vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 256 integer map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 256 integer unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 256 integer flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 256 integer vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 256 integer map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 256 integer unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 256 integer flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 4 string vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 4 string map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 4 string unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 4 string flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 4 string vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 4 string map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 4 string unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 4 string flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 4 string vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 4 string map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 4 string unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 4 string flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 4 string vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 4 string map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 4 string unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 4 string flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 16 string vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 16 string map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 16 string unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 16 string flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 16 string vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 16 string map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 16 string unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 16 string flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 16 string vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 16 string map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 16 string unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 16 string flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 16 string vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 16 string map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 16 string unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 16 string flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 64 string vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 64 string map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 64 string unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 64 string flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 64 string vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 64 string map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 64 string unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 64 string flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 64 string vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 64 string map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 64 string unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 64 string flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 64 string vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 64 string map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 64 string unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 64 string flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 256 string vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 256 string map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 256 string unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 256 string flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 256 string vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 256 string map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 256 string unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 256 string flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 256 string vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 256 string map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 256 string unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 256 string flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 256 string vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 256 string map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 256 string unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 256 string flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 4 string vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 4 string map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 4 string unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 4 string flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 4 string vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 4 string map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 4 string unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 4 string flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 4 string vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 4 string map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 4 string unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 4 string flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 4 string vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 4 string map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 4 string unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 4 string flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 16 string vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 16 string map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 16 string unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 16 string flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 16 string vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 16 string map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 16 string unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 16 string flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 16 string vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 16 string map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 16 string unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 16 string flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 16 string vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 16 string map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 16 string unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 16 string flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 64 string vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 64 string map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 64 string unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 64 string flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 64 string vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 64 string map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 64 string unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 64 string flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 64 string vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 64 string map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 64 string unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 64 string flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 64 string vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 64 string map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 64 string unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 64 string flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 256 string vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 256 string map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 256 string unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 256 string flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 256 string vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 256 string map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 256 string unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 256 string flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 256 string vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 256 string map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 256 string unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 256 string flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 256 string vector construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 256 string map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 256 string unordered_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 256 string flat_map construct-once lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 4 integer vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 4 integer map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 4 integer unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 4 integer flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 4 integer vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 4 integer map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 4 integer unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 4 integer flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 4 integer vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 4 integer map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 4 integer unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 4 integer flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 4 integer vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 4 integer map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 4 integer unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 4 integer flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 16 integer vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 16 integer map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 16 integer unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 16 integer flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 16 integer vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 16 integer map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 16 integer unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 16 integer flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 16 integer vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 16 integer map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 16 integer unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 16 integer flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 16 integer vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 16 integer map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 16 integer unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 16 integer flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 64 integer vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 64 integer map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 64 integer unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 64 integer flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 64 integer vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 64 integer map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 64 integer unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 64 integer flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 64 integer vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 64 integer map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 64 integer unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 64 integer flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 64 integer vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 64 integer map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 64 integer unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 64 integer flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 256 integer vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 256 integer map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 256 integer unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 256 integer flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 256 integer vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 256 integer map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 256 integer unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 256 integer flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 256 integer vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 256 integer map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 256 integer unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 256 integer flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 256 integer vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 256 integer map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 256 integer unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 256 integer flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 4 string vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 4 string map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 4 string unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 4 string flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 4 string vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 4 string map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 4 string unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 4 string flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 4 string vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 4 string map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 4 string unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 4 string flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 4 string vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 4 string map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 4 string unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 4 string flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 16 string vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 16 string map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 16 string unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 16 string flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 16 string vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 16 string map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 16 string unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 16 string flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 16 string vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 16 string map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 16 string unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 16 string flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 16 string vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 16 string map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 16 string unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 16 string flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 64 string vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 64 string map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 64 string unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 64 string flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 64 string vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 64 string map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 64 string unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 64 string flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 64 string vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 64 string map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 64 string unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 64 string flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 64 string vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 64 string map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 64 string unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 64 string flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 256 string vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 256 string map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 256 string unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 256 string flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 256 string vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 256 string map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 256 string unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 256 string flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 256 string vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 256 string map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 256 string unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 256 string flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 256 string vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 256 string map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 256 string unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 256 string flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 4 string vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 4 string map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 4 string unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 4 string flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 4 string vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 4 string map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 4 string unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 4 string flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 4 string vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 4 string map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 4 string unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 4 string flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 4 string vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 4 string map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 4 string unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 4 string flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 16 string vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 16 string map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 16 string unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 16 string flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 16 string vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 16 string map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 16 string unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 16 string flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 16 string vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 16 string map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 16 string unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 16 string flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 16 string vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 16 string map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 16 string unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 16 string flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 64 string vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 64 string map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 64 string unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 64 string flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 64 string vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 64 string map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 64 string unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 64 string flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 64 string vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 64 string map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 64 string unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 64 string flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 64 string vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 64 string map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 64 string unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 64 string flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 256 string vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 256 string map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 256 string unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 256 string flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 256 string vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 256 string map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 256 string unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 256 string flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 256 string vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 256 string map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 256 string unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 256 string flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 256 string vector construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 256 string map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 256 string unordered_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 256 string flat_map construct-once lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 4 integer vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 4 integer map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 4 integer unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 4 integer flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 4 integer vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 4 integer map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 4 integer unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 4 integer flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 4 integer vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 4 integer map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 4 integer unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 4 integer flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 4 integer vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 4 integer map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 4 integer unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 4 integer flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 16 integer vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 16 integer map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 16 integer unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 16 integer flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 16 integer vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 16 integer map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 16 integer unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 16 integer flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 16 integer vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 16 integer map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 16 integer unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 16 integer flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 16 integer vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 16 integer map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 16 integer unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 16 integer flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 64 integer vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 64 integer map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 64 integer unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 64 integer flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 64 integer vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 64 integer map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 64 integer unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 64 integer flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 64 integer vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 64 integer map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 64 integer unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 64 integer flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 64 integer vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 64 integer map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 64 integer unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 64 integer flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 256 integer vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 256 integer map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 256 integer unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 256 integer flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 256 integer vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 256 integer map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 256 integer unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 256 integer flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 256 integer vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 256 integer map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 256 integer unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 256 integer flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 256 integer vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 256 integer map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 256 integer unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 256 integer flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 4 string vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 4 string map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 4 string unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 4 string flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 4 string vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 4 string map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 4 string unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 4 string flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 4 string vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 4 string map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 4 string unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 4 string flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 4 string vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 4 string map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 4 string unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 4 string flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 16 string vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 16 string map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 16 string unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 16 string flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 16 string vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 16 string map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 16 string unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 16 string flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 16 string vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 16 string map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 16 string unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 16 string flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 16 string vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 16 string map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 16 string unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 16 string flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 64 string vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 64 string map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 64 string unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 64 string flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 64 string vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 64 string map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 64 string unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 64 string flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 64 string vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 64 string map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 64 string unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 64 string flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 64 string vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 64 string map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 64 string unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 64 string flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 256 string vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 256 string map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 256 string unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 256 string flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 256 string vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 256 string map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 256 string unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 256 string flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 256 string vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 256 string map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 256 string unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 256 string flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 256 string vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 256 string map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 256 string unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 256 string flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 4 string vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 4 string map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 4 string unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 4 string flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 4 string vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 4 string map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 4 string unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 4 string flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 4 string vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 4 string map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 4 string unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 4 string flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 4 string vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 4 string map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 4 string unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 4 string flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 16 string vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 16 string map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 16 string unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 16 string flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 16 string vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 16 string map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 16 string unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 16 string flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 16 string vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 16 string map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 16 string unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 16 string flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 16 string vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 16 string map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 16 string unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 16 string flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 64 string vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 64 string map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 64 string unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 64 string flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 64 string vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 64 string map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 64 string unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 64 string flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 64 string vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 64 string map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 64 string unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 64 string flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 64 string vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 64 string map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 64 string unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 64 string flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 256 string vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 256 string map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 256 string unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 256 string flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 256 string vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 256 string map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 256 string unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 256 string flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 256 string vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 256 string map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 256 string unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 256 string flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 256 string vector construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 256 string map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 256 string unordered_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 256 string flat_map construct-sporadic lookup-continuously
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 4 integer vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 4 integer map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 4 integer unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 4 integer flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 4 integer vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 4 integer map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 4 integer unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 4 integer flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 4 integer vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 4 integer map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 4 integer unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 4 integer flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 4 integer vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 4 integer map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 4 integer unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 4 integer flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 16 integer vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 16 integer map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 16 integer unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 16 integer flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 16 integer vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 16 integer map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 16 integer unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 16 integer flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 16 integer vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 16 integer map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 16 integer unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 16 integer flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 16 integer vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 16 integer map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 16 integer unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 16 integer flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 64 integer vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 64 integer map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 64 integer unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 64 integer flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 64 integer vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 64 integer map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 64 integer unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 64 integer flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 64 integer vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 64 integer map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 64 integer unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 64 integer flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 64 integer vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 64 integer map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 64 integer unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 64 integer flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 256 integer vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 256 integer map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 256 integer unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10 256 integer flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 256 integer vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 256 integer map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 256 integer unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 100 256 integer flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 256 integer vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 256 integer map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 256 integer unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 1000 256 integer flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 256 integer vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 256 integer map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 256 integer unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_integer.txt 10 10000 256 integer flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 4 string vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 4 string map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 4 string unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 4 string flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 4 string vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 4 string map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 4 string unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 4 string flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 4 string vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 4 string map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 4 string unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 4 string flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 4 string vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 4 string map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 4 string unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 4 string flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 16 string vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 16 string map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 16 string unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 16 string flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 16 string vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 16 string map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 16 string unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 16 string flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 16 string vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 16 string map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 16 string unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 16 string flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 16 string vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 16 string map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 16 string unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 16 string flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 64 string vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 64 string map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 64 string unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 64 string flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 64 string vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 64 string map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 64 string unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 64 string flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 64 string vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 64 string map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 64 string unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 64 string flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 64 string vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 64 string map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 64 string unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 64 string flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 256 string vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 256 string map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 256 string unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10 256 string flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 256 string vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 256 string map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 256 string unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 100 256 string flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 256 string vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 256 string map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 256 string unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 1000 256 string flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 256 string vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 256 string map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 256 string unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string10.txt 10 10000 256 string flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 4 string vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 4 string map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 4 string unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 4 string flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 4 string vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 4 string map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 4 string unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 4 string flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 4 string vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 4 string map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 4 string unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 4 string flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 4 string vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 4 string map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 4 string unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 4 string flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 16 string vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 16 string map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 16 string unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 16 string flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 16 string vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 16 string map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 16 string unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 16 string flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 16 string vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 16 string map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 16 string unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 16 string flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 16 string vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 16 string map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 16 string unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 16 string flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 64 string vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 64 string map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 64 string unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 64 string flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 64 string vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 64 string map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 64 string unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 64 string flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 64 string vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 64 string map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 64 string unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 64 string flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 64 string vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 64 string map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 64 string unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 64 string flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 256 string vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 256 string map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 256 string unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10 256 string flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 256 string vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 256 string map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 256 string unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 100 256 string flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 256 string vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 256 string map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 256 string unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 1000 256 string flat_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 256 string vector construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 256 string map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 256 string unordered_map construct-sporadic lookup-sporadic
call ..\Release\pick.a.container.exe ../keys/keys_string32.txt 10 10000 256 string flat_map construct-sporadic lookup-sporadic
